Btn hovers added and tiny modification to html
gmagnenat/equalizer-landing-page pull request #43
Opened 2022-08-01 21:42 UTC by KingLyrics

I added an ID to specifically identify facebook logo... I could have used another way may with psuedo but i kept missing it. Using first of child or so on. If you feel you want us to change it that would be very okay. I am still learning after all. But the hovers are working quite well.

2022-08-01 21:53 UTC, KingLyrics commented
Been battling the facebook hover effect for a while now. Your help would be very much appreciated :)

2022-08-02 12:38 UTC, gmagnenat requested changes

2022-08-02 12:38 UTC, gmagnenat commented on src/sass/main.scss
> +		&:hover{
cool 😎 you can add a little transition for the hover color. Makes it more smooth

2022-08-02 12:38 UTC, gmagnenat commented on src/sass/main.scss
> +			color: $clr-neutral-100;
the color of the text here should be neutral-800 (dark)

2022-08-02 12:38 UTC, gmagnenat commented on src/sass/main.scss
> +		#facebook:hover{
By the design, I think all links have the same color on hover. So you don't need unique ID here.
Try to use a css filter instead.

2022-08-02 13:13 UTC, KingLyrics commented on src/sass/main.scss
> +		&:hover{
Done and dusted

2022-08-02 13:14 UTC, KingLyrics commented on src/sass/main.scss
> +			color: $clr-neutral-100;
Corrected

2022-08-02 13:22 UTC, KingLyrics commented on src/sass/main.scss
> +		#facebook:hover{
Okay, a little unsure about how to go about this one. Not familiar with the filter property.

2022-08-02 13:45 UTC, gmagnenat commented on src/sass/main.scss
> +		#facebook:hover{
@KingLyrics I added the hover rule with filter. You can check it out in the last commit on this branch

2022-08-02 13:47 UTC, gmagnenat commented on src/sass/main.scss
> +		#facebook:hover{
You can check tools like this to help find the value. https://isotropic.co/tool/hex-color-to-css-filter/

2022-08-02 13:50 UTC, gmagnenat approved these changes
All good !

2022-08-02 13:50 UTC, merged